import type {
  AICFORecommendation,
  FinancialMetrics,
  ProfitabilityMetrics,
} from "@/lib/finance";

interface BusinessIntelligenceDashboardProps {
  financialMetrics: FinancialMetrics;
  profitabilityMetrics: ProfitabilityMetrics;
  aiRecommendation: AICFORecommendation;
}

interface MetricCardProps {
  label: string;
  value: string;
  description: string;
}

function formatCurrency(value: number): string {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  }).format(value);
}

function formatPercentage(value: number): string {
  return `${value.toFixed(2)}%`;
}

function formatNumber(value: number): string {
  return new Intl.NumberFormat("en-US", {
    maximumFractionDigits: 2,
  }).format(value);
}

function getRecommendationStyles(
  recommendation: AICFORecommendation["recommendation"],
): string {
  if (recommendation === "accept") {
    return "border-emerald-500/30 bg-emerald-500/10 text-emerald-300";
  }

  if (recommendation === "decline") {
    return "border-red-500/30 bg-red-500/10 text-red-300";
  }

  return "border-amber-500/30 bg-amber-500/10 text-amber-300";
}

function getStatusLabel(
  status: ProfitabilityMetrics["profitabilityStatus"],
): string {
  switch (status) {
    case "highly-profitable":
      return "Highly Profitable";
    case "profitable":
      return "Profitable";
    case "marginal":
      return "Marginal";
    case "unprofitable":
      return "Unprofitable";
  }
}

function MetricCard({
  label,
  value,
  description,
}: MetricCardProps) {
  return (
    <article className="rounded-2xl border border-white/10 bg-slate-900/70 p-5 shadow-lg shadow-black/10">
      <p className="text-sm font-medium text-slate-400">{label}</p>

      <p className="mt-3 text-2xl font-semibold tracking-tight text-white">
        {value}
      </p>

      <p className="mt-2 text-sm leading-6 text-slate-500">
        {description}
      </p>
    </article>
  );
}

export function BusinessIntelligenceDashboard({
  financialMetrics,
  profitabilityMetrics,
  aiRecommendation,
}: BusinessIntelligenceDashboardProps) {
  const recommendationStyles = getRecommendationStyles(
    aiRecommendation.recommendation,
  );

  return (
    <main className="min-h-screen bg-slate-950 text-white">
      <div className="mx-auto w-full max-w-7xl px-4 py-8 sm:px-6 lg:px-8">
        <header className="rounded-3xl border border-white/10 bg-gradient-to-br from-slate-900 to-slate-950 p-6 shadow-2xl shadow-black/20 sm:p-8">
          <div className="flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between">
            <div>
              <p className="text-sm font-semibold uppercase tracking-[0.22em] text-emerald-400">
                Owner Operator Copilot OS
              </p>

              <h1 className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">
                Business Intelligence
              </h1>

              <p className="mt-3 max-w-3xl text-sm leading-6 text-slate-400 sm:text-base">
                Financial intelligence for evaluating load revenue,
                operating costs, profitability, deadhead exposure and
                AI-assisted business decisions.
              </p>
            </div>

            <div className="rounded-2xl border border-white/10 bg-white/5 px-5 py-4">
              <p className="text-xs font-semibold uppercase tracking-widest text-slate-500">
                Profitability status
              </p>

              <p className="mt-2 text-lg font-semibold text-white">
                {getStatusLabel(
                  profitabilityMetrics.profitabilityStatus,
                )}
              </p>

              <p className="mt-1 text-sm text-slate-400">
                Score: {formatNumber(
                  profitabilityMetrics.profitabilityScore,
                )}{" "}
                / 100
              </p>
            </div>
          </div>
        </header>

        <section className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
          <MetricCard
            label="Revenue"
            value={formatCurrency(financialMetrics.revenue)}
            description="Projected gross revenue generated by the load."
          />

          <MetricCard
            label="Operating Costs"
            value={formatCurrency(
              financialMetrics.operatingCosts,
            )}
            description="Estimated total fixed and variable expenses."
          />

          <MetricCard
            label="Net Profit"
            value={formatCurrency(financialMetrics.netProfit)}
            description="Projected revenue remaining after expenses."
          />

          <MetricCard
            label="Profit Margin"
            value={formatPercentage(
              financialMetrics.profitMargin,
            )}
            description="Percentage of revenue retained as profit."
          />
        </section>

        <section className="mt-4 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
          <MetricCard
            label="Revenue Per Mile"
            value={formatCurrency(
              financialMetrics.revenuePerMile,
            )}
            description="Revenue measured across loaded and deadhead miles."
          />

          <MetricCard
            label="Cost Per Mile"
            value={formatCurrency(
              financialMetrics.costPerMile,
            )}
            description="Average operating cost across all trip miles."
          />

          <MetricCard
            label="Profit Per Mile"
            value={formatCurrency(
              financialMetrics.profitPerMile,
            )}
            description="Projected profit generated per total mile."
          />

          <MetricCard
            label="Operating Ratio"
            value={formatPercentage(
              profitabilityMetrics.operatingRatio,
            )}
            description="Percentage of revenue consumed by operating costs."
          />
        </section>

        <section className="mt-6 grid gap-6 lg:grid-cols-[1.15fr_0.85fr]">
          <article className="rounded-3xl border border-white/10 bg-slate-900/70 p-6 shadow-xl shadow-black/10">
            <div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
              <div>
                <p className="text-sm font-semibold uppercase tracking-[0.2em] text-slate-500">
                  AI CFO
                </p>

                <h2 className="mt-2 text-2xl font-semibold">
                  Financial Recommendation
                </h2>
              </div>

              <span
                className={`w-fit rounded-full border px-4 py-2 text-sm font-semibold uppercase tracking-wider ${recommendationStyles}`}
              >
                {aiRecommendation.recommendation}
              </span>
            </div>

            <div className="mt-6 rounded-2xl border border-white/10 bg-slate-950/60 p-5">
              <h3 className="text-xl font-semibold text-white">
                {aiRecommendation.title}
              </h3>

              <p className="mt-3 leading-7 text-slate-300">
                {aiRecommendation.explanation}
              </p>

              <p className="mt-4 text-sm text-slate-500">
                Recommendation confidence:{" "}
                {formatPercentage(aiRecommendation.confidence)}
              </p>
            </div>

            <div className="mt-6">
              <h3 className="text-sm font-semibold uppercase tracking-widest text-slate-500">
                Recommended actions
              </h3>

              <div className="mt-4 grid gap-3">
                {aiRecommendation.actionItems.map(
                  (actionItem, index) => (
                    <div
                      key={`${actionItem}-${index}`}
                      className="flex items-start gap-3 rounded-xl border border-white/10 bg-white/[0.03] px-4 py-3"
                    >
                      <span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-emerald-500/10 text-xs font-semibold text-emerald-300">
                        {index + 1}
                      </span>

                      <p className="pt-0.5 text-sm leading-6 text-slate-300">
                        {actionItem}
                      </p>
                    </div>
                  ),
                )}
              </div>
            </div>
          </article>

          <aside className="space-y-6">
            <article className="rounded-3xl border border-white/10 bg-slate-900/70 p-6 shadow-xl shadow-black/10">
              <p className="text-sm font-semibold uppercase tracking-[0.2em] text-slate-500">
                Route Economics
              </p>

              <div className="mt-5 space-y-4">
                <div className="flex items-center justify-between border-b border-white/10 pb-4">
                  <span className="text-sm text-slate-400">
                    Loaded miles
                  </span>

                  <span className="font-semibold text-white">
                    {formatNumber(financialMetrics.loadedMiles)}
                  </span>
                </div>

                <div className="flex items-center justify-between border-b border-white/10 pb-4">
                  <span className="text-sm text-slate-400">
                    Deadhead miles
                  </span>

                  <span className="font-semibold text-white">
                    {formatNumber(financialMetrics.deadheadMiles)}
                  </span>
                </div>

                <div className="flex items-center justify-between border-b border-white/10 pb-4">
                  <span className="text-sm text-slate-400">
                    Total miles
                  </span>

                  <span className="font-semibold text-white">
                    {formatNumber(financialMetrics.totalMiles)}
                  </span>
                </div>

                <div className="flex items-center justify-between">
                  <span className="text-sm text-slate-400">
                    Deadhead percentage
                  </span>

                  <span className="font-semibold text-white">
                    {formatPercentage(
                      profitabilityMetrics.deadheadPercentage,
                    )}
                  </span>
                </div>
              </div>
            </article>

            <article className="rounded-3xl border border-white/10 bg-slate-900/70 p-6 shadow-xl shadow-black/10">
              <p className="text-sm font-semibold uppercase tracking-[0.2em] text-slate-500">
                Break-Even Intelligence
              </p>

              <div className="mt-5 space-y-4">
                <div>
                  <p className="text-sm text-slate-400">
                    Break-even revenue
                  </p>

                  <p className="mt-1 text-xl font-semibold text-white">
                    {formatCurrency(
                      profitabilityMetrics.breakEvenRevenue,
                    )}
                  </p>
                </div>

                <div>
                  <p className="text-sm text-slate-400">
                    Break-even rate per mile
                  </p>

                  <p className="mt-1 text-xl font-semibold text-white">
                    {formatCurrency(
                      profitabilityMetrics.breakEvenRatePerMile,
                    )}
                  </p>
                </div>

                <div>
                  <p className="text-sm text-slate-400">
                    Deadhead cost impact
                  </p>

                  <p className="mt-1 text-xl font-semibold text-white">
                    {formatCurrency(
                      profitabilityMetrics.deadheadCostImpact,
                    )}
                  </p>
                </div>

                <div>
                  <p className="text-sm text-slate-400">
                    Revenue gap to target
                  </p>

                  <p className="mt-1 text-xl font-semibold text-white">
                    {formatCurrency(
                      profitabilityMetrics.revenueGap,
                    )}
                  </p>
                </div>
              </div>
            </article>
          </aside>
        </section>
      </div>
    </main>
  );
}