import type {
  FinancialMetrics,
  ProfitabilityMetrics,
} from "@/lib/finance";

import { AppCard } from "@/components/ui";

interface FinancialSummaryCardProps {
  financialMetrics: FinancialMetrics;
  profitabilityMetrics: ProfitabilityMetrics;
  resultsRef: React.RefObject<HTMLDivElement | null>;
}

interface FinancialMetricCardProps {
  label: string;
  value: string;
  supportingText: string;
}

function formatCurrency(value: number): string {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  }).format(value);
}

function formatPercentage(value: number): string {
  return `${value.toFixed(2)}%`;
}

function formatNumber(value: number): string {
  return new Intl.NumberFormat("en-US", {
    maximumFractionDigits: 2,
  }).format(value);
}

function getStatusLabel(
  status: ProfitabilityMetrics["profitabilityStatus"],
): string {
  switch (status) {
    case "highly-profitable":
      return "Highly Profitable";
    case "profitable":
      return "Profitable";
    case "marginal":
      return "Marginal";
    case "unprofitable":
      return "Unprofitable";
  }
}

function FinancialMetricCard({
  label,
  value,
  supportingText,
}: FinancialMetricCardProps) {
  return (
    <AppCard
      tone="subtle"
      className="flex min-h-40 flex-col justify-between"
    >
      <div>
        <p className="text-xs font-semibold uppercase tracking-widest text-slate-500">
          {label}
        </p>

        <p className="mt-3 text-2xl font-semibold tracking-tight text-white">
          {value}
        </p>
      </div>

      <p className="mt-4 text-xs leading-5 text-slate-500">
        {supportingText}
      </p>
    </AppCard>
  );
}

export function FinancialSummaryCard({
  financialMetrics,
  profitabilityMetrics,
  resultsRef,
}: FinancialSummaryCardProps) {
  return (
    <AppCard
      className="scroll-mt-6"
      ref={resultsRef}
    >
      <div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
        <div>
          <p className="text-xs font-semibold uppercase tracking-[0.2em] text-emerald-400">
            Financial Intelligence
          </p>

          <h3 className="mt-2 text-xl font-semibold">
            Active load economics
          </h3>

          <p className="mt-2 text-sm leading-6 text-slate-400">
            Current financial results generated by the expense,
            financial and profitability engines.
          </p>
        </div>

        <AppCard
          tone="subtle"
          padding="sm"
          className="w-fit rounded-2xl"
        >
          <p className="text-[10px] font-semibold uppercase tracking-widest text-slate-500">
            Profitability status
          </p>

          <p className="mt-1 font-semibold text-white">
            {getStatusLabel(
              profitabilityMetrics.profitabilityStatus,
            )}
          </p>

          <p className="mt-1 text-xs text-slate-500">
            Score{" "}
            {formatNumber(
              profitabilityMetrics.profitabilityScore,
            )}{" "}
            / 100
          </p>
        </AppCard>
      </div>

      <div className="mt-6 grid auto-rows-fr gap-4 sm:grid-cols-2 xl:grid-cols-4">
        <FinancialMetricCard
          label="Revenue"
          value={formatCurrency(financialMetrics.revenue)}
          supportingText="Gross revenue offered for the active load."
        />

        <FinancialMetricCard
          label="Operating Costs"
          value={formatCurrency(
            financialMetrics.operatingCosts,
          )}
          supportingText="Projected fixed and variable load expenses."
        />

        <FinancialMetricCard
          label="Net Profit"
          value={formatCurrency(financialMetrics.netProfit)}
          supportingText="Revenue remaining after operating expenses."
        />

        <FinancialMetricCard
          label="Profit Margin"
          value={formatPercentage(
            financialMetrics.profitMargin,
          )}
          supportingText="Percentage of revenue retained as profit."
        />

        <FinancialMetricCard
          label="Revenue Per Mile"
          value={formatCurrency(
            financialMetrics.revenuePerMile,
          )}
          supportingText="Revenue across loaded and deadhead miles."
        />

        <FinancialMetricCard
          label="Cost Per Mile"
          value={formatCurrency(
            financialMetrics.costPerMile,
          )}
          supportingText="Average operating cost across all miles."
        />

        <FinancialMetricCard
          label="Profit Per Mile"
          value={formatCurrency(
            financialMetrics.profitPerMile,
          )}
          supportingText="Projected profit generated per total mile."
        />

        <FinancialMetricCard
          label="Operating Ratio"
          value={formatPercentage(
            profitabilityMetrics.operatingRatio,
          )}
          supportingText="Percentage of revenue consumed by expenses."
        />
      </div>
    </AppCard>
  );
}